#!/bin/bash

rm -f .tests_failed

for DIR in ./*/
do
    cd $DIR
    ./make tests
    [[ -e .tests_failed ]] && touch ../.tests_failed
    cd ..
    sleep 1
done

wait

echo -e "===FINAL REPORT==="

if [[ -f .tests_failed ]]
then
    echo -e "\e[91mSome tests failed\e[39m"
    rm .tests_failed
    exit 1
else
    echo -e "\e[92mAll tests passed\e[39m"
fi
